* MUSA Backend:
This backend periodically requests near miss data from the NASA API, and
restructures it to a more usable format for visualization purposes. The data is
returned sorted from nearest object to farthest. Additionally, it also handles a
similar task for the NASA Astronomy Picture of The Day function for our project. 

** Pre-requisites:
You need an API key from NASA to use this backend. See [[https://api.nasa.gov]],
generate an API key, and save it into a file in the same directory as
=musa-backend.js= called =api.secret=. Additionally, the backend will need access to
a TLS certificate and key, made available in the directory as /selfsigned.crt/ and
/selfsigned.key/. 

** Running:
Run =node musa-backend.js= to start the backend.

** Dependencies:
- Express (Used for HTTPS server).
- Node-Schedule (Used to schedule data updating).
- CORS (Used to enable CORS, if you can imagine.)

** API:
The API for this backend is exceedingly simple. Making a GET request to one of
two endpoints will return the necessary data for each functionality of the site.
All of these are pre-sorted in the correct order.

- / :: This endpoint will return a JSON object with an array of the current near
  misses of the day. The current format of these items is:
  | name | id | size | distance | date |

- /images :: This endpoint will return a JSON object with an array of last seven
  day's APODs. The current format of these items is:
  | title | explanation | date | url |
